owner: YuriyDm123
repo: VISA

sites:
- name: "ping_8.8.8.8"
  url: "dns.google"
  type: globalping
  check: tcp-ping
  port: 53
  location: "Western Europe"

- name: "198.241.150.240"
  url: "198.241.150.240"
  type: globalping
  check: tcp-ping
  port: 443
  location: "Western Europe"

- name: "198.241.184.92"
  url: "198.241.184.92"
  type: globalping
  check: tcp-ping
  port: 443
  location: "Western Europe"

- name: "198.217.243.16"
  url: "198.217.243.16"
  type: globalping
  check: tcp-ping
  port: 443
  location: "Western Europe"
