owner: YuriyDm123
repo: VISA

sites:
  - name: "198.241.184.92"
    url: 8.8.8.8
    check-type: globalping
    globalping:
      type: tcp
      port: 443
      from: "Western Europe, Russia"

      
