owner: YuriyDm123
repo: VISA

sites:
  - name: "Мой Сервер"
    url: 198.241.184.92
    check-type: globalping
    globalping:
      type: tcp
      port: 443
      from: "Western Europe, Russia"

      
