on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    name: Uptime CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Uptime Monitor
        uses: upptime/uptime-monitor@v1
        continue-on-error: true
        with:
          command: "update"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GLOBALPING_TOKEN: ${{ secrets.GLOBALPING_TOKEN }}
